version: '3.8'

services:
  # Database service
  db:
    image: mysql:8.0.26  # Using a specific version of MySQL
    container_name: fiver-db
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: sandr
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  all_classes:
    build:
      context: ./all_classes
      dockerfile: Dockerfile
    container_name: allclasses-service

  # Spring Boot services
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiver-db:3306/sandr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  wishlist:
    build:
      context: ./wishlist
      dockerfile: Dockerfile
    container_name: wishlist-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiver-db:3306/sandr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    container_name: cart-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiver-db:3306/sandr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiver-db:3306/sandr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  product:
    build:
      context: ./product/product
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiver-db:3306/sandr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  review:
    build:
      context: ./review
      dockerfile: Dockerfile
    container_name: review-service
    ports:
      - "8086:8086"  # Changed from 8086 to avoid port conflict with product service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiver-db:3306/sandr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  order:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiver-db:3306/sandr
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    depends_on:
      - db

  # React Frontend
  frontend:
    build:
      context: ./project-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"

volumes:
  db_data:
